name: aspnet_mvc
description: "A MVC structure based on ASP.NET MVC"
version: 0.0.2
homepage: 

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fake_reflection: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: